// AUTO-GENERATED by tools/gen-adapters.mjs from <firmware>/bin/config.d/lora-*.yaml
// (CH341 USB adapters only — driveable over WebUSB). Do not edit by hand.
// Regenerate: npm run gen:adapters

export const ADAPTERS = {
  "meshstick-1262": {
    "id": "meshstick-1262",
    "label": "Lora Meshstick SX1262",
    "support": "official",
    "module": 3,
    "vid": 6790,
    "pid": 21778,
    "dio2": 0,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 2,
      "BUSY": 4
    }
  },
  "usb-meshstick-1262": {
    "id": "usb-meshstick-1262",
    "label": "meshstick-1262",
    "support": "official",
    "module": 3,
    "vid": 6790,
    "pid": 21778,
    "dio2": 1,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 2,
      "BUSY": 4,
      "RXEN": 1
    }
  },
  "usb-meshtoad-e22": {
    "id": "usb-meshtoad-e22",
    "label": "meshtoad-e22",
    "support": "official",
    "module": 3,
    "vid": 6790,
    "pid": 21778,
    "dio2": 1,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 2,
      "BUSY": 4,
      "RXEN": 1
    }
  },
  "piggystick-lr1121": {
    "id": "piggystick-lr1121",
    "label": "Lora Meshstick SX1262",
    "support": "community",
    "module": 8,
    "vid": 6790,
    "pid": 21778,
    "dio2": 0,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 2,
      "BUSY": 4
    }
  },
  "pinedio-usb-sx1262": {
    "id": "pinedio-usb-sx1262",
    "label": "Pinedio USB SX1262",
    "support": "deprecated",
    "module": 3,
    "vid": 6790,
    "pid": 21778,
    "dio2": 0,
    "tcxo_mv": 0,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 10
    }
  },
  "usb-umesh-1262-30dbm": {
    "id": "usb-umesh-1262-30dbm",
    "label": "umesh-1262-30dbm",
    "support": "community",
    "module": 3,
    "vid": 6790,
    "pid": 21778,
    "dio2": 1,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 1,
      "BUSY": 4,
      "RXEN": 2
    }
  },
  "usb-umesh-1268-30dbm": {
    "id": "usb-umesh-1268-30dbm",
    "label": "umesh-1268-30dbm",
    "support": "community",
    "module": 4,
    "vid": 6790,
    "pid": 21778,
    "dio2": 1,
    "tcxo_mv": 1800,
    "spi_hz": 2000000,
    "pins": {
      "CS": 0,
      "IRQ": 6,
      "RESET": 1,
      "BUSY": 4,
      "RXEN": 2
    }
  }
};

// Apply a chosen adapter to the wasm node BEFORE wasm_setup(), via the
// wasm_set_lora_* exports. Pass null/undefined -> firmware's MeshToad default.
export function applyAdapter(Module, a) {
  if (!a) return;
  const C = (fn, types, args) => Module.ccall(fn, null, types, args);
  C("wasm_set_lora_module", ["number"], [a.module]);
  if (a.vid && a.pid) C("wasm_set_lora_usb_ids", ["number", "number"], [a.vid, a.pid]);
  C("wasm_set_lora_dio_config", ["number", "number"], [a.dio2 | 0, a.tcxo_mv | 0]);
  if (a.spi_hz) C("wasm_set_lora_spi_speed", ["number"], [a.spi_hz]);
  for (const [name, pin] of Object.entries(a.pins || {}))
    C("wasm_set_lora_pin", ["string", "number"], [name, pin]);
}
